= Git och GitHub

Kunskaper relaterat till versionshantering (SCM) med hjälp av git. Vetskap om att det finns alternativa VCS än git.

Kunskaper relaterat till jobba mot en centraliserad platform för SCM och projekthantering. I denna dokumentationen är github platformen som utgås ifrån.

== Git teori

Kunskaper om designen bakom git och vilka datastrukturer som används.

Kunskaper om att jobba mot en centraliserad remote (client-server).

=== Varför?

För att kunna förstå teorin bakom kommandon som används.

För att kunna dela kod med andra utvecklare.

=== Vad?

.Koncept:
* Datastrukturer
   - Mutable index
   - Object database
* Refs
   - HEAD
   - branches
   - tags
* Remotes
* Bare repositories

.Kommandon:
* git remote
* git fetch
* git push
* git pull
* git clone
* gh repo create


== Git CLI

Kunskap om vanliga kommandon och växlar för git.

=== Varför?

Git är i grunden terminalbaserat. Många grafiska utvecklingsverktyg saknar funktionalitet från Git CLI.

=== Vad?

.Kommandon
* git status
* git add
* git reset
* git commit
* git restore
* git log
* git branch
* git checkout
* git rm
* git merge
* git rebase
* git stash
* git cherry-pick

== Git arbetssätt

Kunskaper om att använda git som ett kollaborativt verktyg genom ett arbetsflöde.

=== Varför?

För att kunna jobba på samma kodbas med flera utvecklare.

=== Vad?

Kunna jobba med branches och git flow. Lösa merge conflicts.

.Branches:
* master
* develop
* feature
* release
* hotfix

.Koncept:
* Merge conflicts
* Diverging git history

== Issues

För att skapa tasks med labels och en assignee i github platformen.

=== Varför?

För att kunna jobba med issue tracking i git flow arbetsflödet.

=== Vad?

.Koncept

* Github issues

== Projects

Verktyg för projekthantering och skapa kanban boards för organisera issues.

=== Varför?

För att kunna spåra status av issues.

=== Vad?

.Koncept:
* Project boards

== Pull requests

Kunskaper om hur pull/merge requests används.

=== Varför?

För att kunna uppbehålla en konsekvent kodstandard och kodkvalité genom manuella och automatiserade code reviews.

=== Vad?

.Koncept:
* Pull requesuts

.Kommandon:
* gh pr create
