= Versionshantering

.Planering Git
[%collapsible]
====
.Tillfälle 1
 * Genomgång och intro till versionshantering
 * Genomgång av flödet från att skapa ett repository i Github webbsidan till att lösa merge-problem i delade repositories.
 * Övning: Eleverna skapar repositories där de skapar och löser merge-konflikter.
 * Arbeta med materialet till Github flow

.Tillfälle 2
 * Kort om Github issues + Github project boards
 * Eleverna arbetar med Git för källkod och om de vill `Issues` + `Github project boards` projekt 1

.Tillfälle 3
 * Versionsnummer
 * Github flow
 * Genomngång + övningar

.Tillfälle 4
 * Workshop: git extras
====

För att skapa spårbarhet och enkelare kunna hitta när ett fel blev till i ett mjukvaruprojekt versionshanteras i princip alltid källkod (och dokumentation) och Git är sedan ca tio år det vanligaste versionshanteringssystemet. Kapitlet ger kunskaper om versionshantering med hjälp av Git och Github. 

Git är ett distribuerat versionssystem vilket betyder att alla filer och data finns på alla klienter. Du arbetar med dina ändringar lokalt på din dator där du kan arbeta med lokala versioner (`add` & `commit`). Sedan laddas alla versioner upp och till servern (`push`) och ner (`pull`) från servern. 

Det kan ibland uppstå problem med att `merga` kod även med Github och vi kommer ta upp strategier för det senare. Långt innan Git använde man istället system som låste filer som ändrades i tills den som ändrat släppt låset. 


.En kort intro till versionshantering & Git icon:play[]

* https://git-scm.com/video/what-is-version-control[Vad är versionshantering?]
* https://git-scm.com/video/what-is-git[Vad är Git?] 
* https://git-scm.com/video/get-going[Börja med Git]

== How-to: Intro till Git icon:map[]
En kort guide för att kunna skapa ett repository på Github dit du sedan kan ladda upp dina ändringar.

[NOTE] 
.Problem med inloggning eller authentisering?
==== 
Beroende på om ni loggat in i Github tidigare har authentiseringen lagrats på olika ställen i din dator. Det enklaste sättet att fixa det verkar vara att använda `github-cli` som ni installerar med `brew install gh`.

Logga ut: `gh auth logout`
Logga in: `gh auth login`

icon:book[] Manualsidor: `man gh-auth`
====

=== 1. Skapa och ladda ner ett repository på Github
Logga in på Github och skapa ett nytt repository i webbgränssnittet. Döp det till `learning-vcs`. Lägg till README-filen (viktigt), Gör det privat och låt övrigt vara. Addressen till repositoriet finns både via `HTTPS` och `SSH`. Väljer du `HTTPS` får du göra `authentiseringen` (inloggningen) i webbläsaren, annars måste du skapa `SSH-nycklar` manuellt och ladda upp till ditt Github-konto.

Använd kommandot `git clone` i terminalen för att hämta ett repository till mappen du står i. Glöm inte ersätta `ntijoh-ola-lindberg` med din användare. 

----
git clone https://github.com/ntijoh-ola-lindberg/learning-vcs.git
----

För att se vilka filer som ändrats jämfört med filerna på servern används kommmandot `git status` och för att ladda ner uppdateringar från servern `git pull`.

icon:book[] Manualsidor: `man git-clone`, `man git-status`, `man git-pull`

=== 2. Lägg in en ny fil till i repository
Skapa filen `fil1.txt` och kolla status (`git status`). Din nya fil står som `Untracked` vilket betyder att den finns lokalt i mappen men `git` vet inte om att den finns.

Lägg till filen till `git` med `git add fil1.txt` vilket gör att `git` vet att filen finns. Med `git status` ser du att filen nu står som `Changes to be committed`.

En `commit` betyder att nuvarande version av filen är lagrad till `git`. Det går först nu att backa ändringar. Normalt görs en `commit` minst varje gånge en `todo` är avklarad. Lägg till filen med `git commit -m "Skapade dokumentet"`. 

Kolla status (`git status`). Din lokala version av repot är nu före serverns version av repot. Dina ändringar och versioner finns lokalt på datorn men inte på servern.

icon:book[] Manualsidor: `man git-add`, `man git-commit`

=== 3. Uppdatera en fil
Öppna, ändra och spara filen `fil1.txt`. Vad säger: `git status`?

Kör: `git commit -m "Skrev första stycket"` Sparas ändringarna till repositoriet?

Att spara ändringar i git är en tvåstegsraket. Först lägger du till vad som ska sparas med `git add` och sedan sparar du versionen med `git commit`. Kombinera de med `git commit -am "Skrev första stycket"`

=== 4. Ladda upp dina filer till Github
Ladda upp dina ändringar till Github med: `git push`. Försäkra dig om att de finns genom att öppna webbläsaren och se att ändringarna syns.

Se historiken med `git log --oneline` eller överkursvarianten: `git log --graph --decorate --abbrev-commit --all --pretty=oneline`

icon:book[] Manualsidor: `man git-push` & `man git-log`

.Läs icon:book[]
* https://education.github.com/git-cheat-sheet-education.pdf[Git cheat sheet]
* https://git-scm.com/book/[Den officiella Git-boken]

=== Git 1 övningar + quiz icon:graduation-cap[]

 * Gör några ändringar till i din fil. Ladda upp några versioner. Kolla på github så du ser alla versioner.
 * Lägg till fler filer och mappar. Kolla på Github så du ser dem.
 * Vad gör: `git add .` och `git add *` ?
 * Gör Git quiz 1

== Arbeta med delad kod i Git
Det finns minst två olika modeller för att samarbeta via Github. Ni kan antingen bjuda in alla som arbetar på projektet som collaborators via Github webbsidan. Detta funkar bäst till mindre projekt eller framförallt till projekt med färre deltagare.

I större projekt används oftast `forks` där vem som helst kan göra en kopia (`fork`) på ett repository, arbeta i det och sedan be projektet `merga` in in ändringarna med en `pull request`.

=== Delat repository
I Githubs gränssnitt lägger ni till de användare som ska kunna skriva repositoriet. Fördelen är att det är väldigt enkelt. Nackdelen är att det inte finns någon speciell strategi för att hantera `merge conflicts`. De hanteras bäst genom att alla `pushar` och `pullar` kod ofta.

Kallas också `Shared repository model` eller `Centralized workflow`.

Läs: https://www.atlassian.com/git/tutorials/comparing-workflows#centralized-workflow[Centralized Workflow - Bitbucket] icon:book[]

=== Delat repository övningar icon:graduation-cap[]
Skapa ett repository som ni delar mellan er. Utforska och arbeta med det. Skapa skapa merge-konflikter och lär er verktygen för att lösa dem.

=== Merga filer i Git #todo#
Det går att använda VSCode som diff / merge-verktyg: https://www.roboleary.net/vscode/2020/09/15/vscode-git.html

=== Github flow
När du lägger till en feature är ett vanligt sätt i Git-projekt att du skapar en branch, gör dina ändringar och sedan mergar tillbaka ändringarna till huvudkoden. Det finns flera fördelar. Bland annat skapas en isolerad miljö där du kan testa dina ändringar i lugn och ro utan att riskera att röra något i övriga projektet.

Ungefär samma strategier kallas också för `Feature branch workflow`, `Branching och merging` eller `Fork and pull`. 

.Föreläsning icon:building[]
* Versionsnummer & GitHub flow

.Läs icon:book[]
* https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow[Feature branch workflow - Bitbucket]  
* https://www.atlassian.com/git/tutorials/using-branches/git-checkout[Git checkout branch - Bitbucket]
* https://www.atlassian.com/git/tutorials/using-branches/git-merge[Git merge - Bitbucket]

==== How-to: Github flow icon:map[] 

Som standard på Github får alla repositories en branch som heter `main`.

Skapa en ny och byt aktiv branch till din nya med kommandot: `git checkout -b ny-branch`. Se vilka branches som finns i repositoryt på din dator: `git branch`. Byter tillbaka till main: `git checkout main`.

När du arbetat färdigt gör du som vanligt, `git commit -ma "Ny feature"`. Du behöver dessutom ladda upp din nya branch till servern (den finns än så länge bara på din dator) och då måste du berätta till var den ska pushas: `git push --set-upstream origin ny-branch`.

När du arbetat färdigt i din nya branch är det dags att merga den till main. I många projekt är detta en tvåstegsraket. Först öppnas en Pull Request. Efter review mergas den. För att skapa `pull requests` anväds https://cli.github.com/manual/gh_pr_create[`gh pr create ny-pull-request`] men oftast behövs mer information som t.ex. kommentarer och många använder github.com för att göra `PR`.

När du mergat din branch kan du ta bort den med `git branch -d ny-branch`. Den försvinner lokalt men finns kvar på Github. Titta under branches i ditt repository på github.com.

`git diff` visar vilka ändringar som gjorts sedan commit. Det går även att jämföra olika branches.

=== Arbetsmetoder med Git flow

.GitHub project management
Tl;DR.
Använd Github Project Boards som kanban

Skapa issues för allt.
Assigna medlemmar till issues.
Skapa en branch för varje issue du jobbar med. Följ en naming convention.
Skapa en pull request för din branch.
Pull requests måste genomgå code review.

* https://docs.github.com/en/issues/tracking-your-work-with-issues/quickstart
* https://docs.github.com/en/get-started/quickstart/github-flow
* https://docs.github.com/en/issues/organizing-your-work-with-project-boards
* https://deepsource.io/blog/git-branch-naming-conventions/

.Miniövningar när allt annat är färdigt
* Ni som inte känner att ni kan göra mer med Git flow / pull requests / issues - uppgiften. Bygg ett shell-script som uppdaterar alla era Git-repositories (dvs kör git pull).
* Ni som är klara med både scriptet och github flow. Bygg ett script som gör GitHub issues från alla TODO-markeringar i er kod. Ni kan tex använda detta: https://github.com/marketplace/actions/todo-to-issue

== Git extra

I Git har vi några saker kvar.
Ni måste inte bli experter på alla dessa koncept men ni ska minst förstå hur de används för att enkelt kunna sätta er in i det senare. Vi kommer hålla små workshops med följande olika verktyg:

* Ändra historik i efterhand: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History 
* git-cherry-pick: https://git-scm.com/docs/git-cherry-pick
* git-bisect: https://git-scm.com/docs/git-bisect
* GitHub CLI: https://github.com/cli/cli
* git-stash: https://git-scm.com/docs/git-stash

.Er uppgift

1). Lär er använda de verktyg ni fått.

2). Lär era klasskamrater använda verktyget. +
Svara minst på följande frågor:

 * Vad är det? / Vad används det till?
 * Hur funkar det? / Hur använder man det?
 * Varför använder man det?

3). Gör en kort demo när ni använder verktyget. Gärna i terminalen. Men inget måste.