= Terminalen och POSIX

Kunskaper relaterat till anvädning av terminalen. Grundläggande kunskaper om olika skal är också nödvändigt. Våra exempel utgår ifrån Zsh eller Bash.

== Navigation

Kunskap om kommandon för att navigera i terminalen och förstå absoluta och relativa sökvägar.

[discrete]
=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.

[discrete]
=== Vad?

.Kommandon:
* pwd
* cd

== Filer

Kunskap om olika filtyper, metadata och förståelse att allting är filer i unix. Använda kommandon för att manipulera filer genom följande operationer:

.Operationer
----
lista, byta namn, skapa, ta bort, läsa, skriva
----

=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.

=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
[source,shell]
----
ls, cat, rm, mv, cp, touch, mkdir, rmdir, less, more, file, du
----

=== Hur?
==== Filsystemet i Unix
En kortfattad beskrivning av Unix-filsystemet. Läs https://tldp.org/LDP/sag/html/dir-tree-overview.html[kapitel 3 i The Linux System Administrator's Guide] för djupare förståelse och detaljer.

[cols="1,4"]
|===
| Sökväg | Beskrivning

|`/bin`
|Binärfiler, dvs. program
 
|`/dev`
| Enheter, t.ex. alla partitioner, hårddiskar och USB-minne

|`/etc`
|Inställningar för t.ex. Wifi och scripts för t.ex. uppstart av servrar.

|`/home`
|Alla vanliga användares hemmappar. +
Root-användaren har sin i `/root`.

|`/mnt``
|Alla monterade lagringsenheter

|`/var/log`
| Loggfiler

|`/proc`
|Hårdvaruinfo om alla enheter som t.ex. nätverkskort och CPU. +
Testa: `cat /proc/cpuinfo`

|===

==== Navigering, filer och mappar
Läs om gundläggande kommandon i terminalen: https://www.fosslinux.com/43292/linux-terminal-commands-to-try-for-a-beginner.htm

==== Kommandon att utforska i terminalen

[cols=">1,3,3"]
|===
| Kommando | Beskrivning | Exempel

| `man`
| Öppna kommandots manualtext. Använd `q` för att återgå.
| `man cd`

| `cd`
| Förflyttning genom mappar
| `cd ~/Desktop`

| `mv`
| Flyttar (eller byter namn) på en fil eller map 
| `mv fil.txt ~/Desktop/fil.txt`

| `clear`
| Rensar terminalskärmen
| `clear`

| `du`
| Räknar hur stor en fil eller mapp är. https://www.oreilly.com/library/view/macintosh-terminal-pocket/9781449328962/re31.html[Läs mer]
| `du fil.txt`

| `file`
| Kommandot tittar på en fil och försöker lista ut vilken sorts fil det är. https://en.wikipedia.org/wiki/File_(command)[Läs mer]
| `file fil.txt`

| `find`
| Går igenom alla filer i en specifik sökväg och går neråt i hierarkin, rekursivt. https://linuxize.com/post/how-to-find-files-in-linux-using-the-command-line/[Läs mer]
| `find /Desktop`

| `wc`
| Räkna mängden ord, rader eller bytes som finns i en textfil. https://www.fosslinux.com/45753/linux-wc-command-examples.htm[Läs mer]
| `wc fil.txt`

|===

== CLI-baserade textredigare

Kunskap att använda en eller flera textredigare ifrån terminalen.

[discrete]
=== Varför?

För att kunna manipulera filer i CLI-baserad gränssnitt utan GUI.

[discrete]
=== Vad?

* nano/vim/emacs

== Unix permissions

Kunskap om filrättigheter och kunna ändra dessa från terminalen.

[discrete]
=== Varför?

För att kunna manipulera filer i CLI-baserad gränssnitt utan GUI.

[discrete]
=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
* sudo
* chmod
* chown
* umask

.Koncept
* Användare
* Grupper

== Kommandon för filtrering av text och filer

Använda CLI program för filtrera text och hitta filer med specifika egenskaper.

[discrete]
=== Varför?

För att kunna söka efter text och filer i CLI-baserat gränssnitt.

[discrete]
=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
* head
* tail
* sort
* wc
* grep
* find

== Streams, redirects och piping

Kunskap om indata/utdata till terminalen, filer och andra program.

[discrete]
=== Varför?

För att kunna använda flera CLI program tillsammans.

[discrete]
=== Vad?

.Standard streams:
* stdin
* stdout
* stderr

Kunna använda följande operatorer.

.Operatorer:
* >
* >>
* 2>
* <
* |

== Processer

Kunskap hur man interagerar med processer från terminalen och hur dessa samspelar med varandra.

[discrete]
=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.

[discrete]
=== Vad?

.Kort kommandon:
- CTRL + C
- CTRL + Z

.Kommandon:
- kill
- ps
- jobs
- fg
- top

.Operatorer:
- &
- &&

== Scripting

Kunskap hur man använder bash scripting.

=== Varför?

För att kunna använda utveckla CLI-baserade verktyg.

=== Vad?

.Koncept:
----
Shebangs, Arguments, Variables, Envrionment variables, Escaping, Subshells, Conditionals
----

.Kommandon:
----
echo
----

== Övrigt

Kunskaper om övriga kommandon.

=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
----
man, alias, history
----
Kommandot `alias` skapar en genväg till kommandon, med eller utan nycklar, för att t.ex. spara tid. Exempel. kör i terminalen:

----
$ alias lista="ls -lah
$ lista
----