= Terminalen och POSIX

Kunskaper relaterat till anvädning av terminalen. Våra exempel utgår ifrån `Zsh` eller `Bash`.

== Navigation

Kunskap om kommandon för att navigera i terminalen och förstå absoluta och relativa sökvägar.

=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.


=== Vad?

.Kommandon:
* pwd
* cd

== Filer

Kunskap om olika filtyper, metadata och förståelse att allting är filer i unix. Använda kommandon för att manipulera filer genom följande operationer:

.Operationer
----
lista, byta namn, skapa, ta bort, läsa, skriva
----

=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.

=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
[source,shell]
----
ls, cat, rm, mv, cp, touch, mkdir, rmdir, less, more, file, du
----

=== Hur?
==== Filsystemet i Unix
En kortfattad beskrivning av Unix-filsystemet. Läs https://tldp.org/LDP/sag/html/dir-tree-overview.html[kapitel 3 i The Linux System Administrator's Guide] för djupare förståelse och detaljer.

[cols="1,4"]
|===
| Sökväg | Beskrivning

|`/bin`
|Binärfiler, dvs. program
 
|`/etc`
|Inställningar för t.ex. Wifi och scripts för t.ex. uppstart av servrar.

|`/home`
|Alla vanliga användares hemmappar. +
Root-användaren har sin i `/root`.

|`/mnt`
|Lagringsenheter som t.ex. partitioner och USB-minne.

|`/var/log`
| Loggfiler

|`/proc`
|Hårdvaruinfo om alla enheter som t.ex. nätverkskort och CPU. +
Testa: `cat /proc/cpuinfo`

|===

==== Navigering, filer och mappar
Läs om gundläggande kommandon i terminalen: https://www.fosslinux.com/43292/linux-terminal-commands-to-try-for-a-beginner.htm

==== Kommandon att utforska i terminalen

[cols=">1,3,3"]
|===
| Kommando | Beskrivning | Exempel

| `man`
| Öppna kommandots manualtext. Använd `q` för att återgå.
| `man cd`

| `cd`
| Förflyttning genom mappar
| `cd ~/Desktop`

| `mv`
| Flyttar (eller byter namn) på en fil eller map 
| `mv fil.txt ~/Desktop/fil.txt`

| `clear`
| Rensar terminalskärmen
| `clear`

| `du`
| Räknar hur stor en fil eller mapp är. https://www.oreilly.com/library/view/macintosh-terminal-pocket/9781449328962/re31.html[Läs mer]
| `du fil.txt`

| `file`
| Kommandot tittar på en fil och försöker lista ut vilken sorts fil det är. https://en.wikipedia.org/wiki/File_(command)[Läs mer]
| `file fil.txt`

| `find`
| Går igenom alla filer i en specifik sökväg och går neråt i hierarkin, rekursivt. https://linuxize.com/post/how-to-find-files-in-linux-using-the-command-line/[Läs mer]
| `find /Desktop`

| `wc`
| Räkna mängden ord, rader eller bytes som finns i en textfil. https://www.fosslinux.com/45753/linux-wc-command-examples.htm[Läs mer]
| `wc fil.txt`

|===

== CLI-baserade textredigare

Kunskap att använda en eller flera textredigare ifrån terminalen.

=== Varför?

För att kunna manipulera filer i CLI-baserad gränssnitt utan GUI.


=== Vad?

* nano/vim/emacs

== Unix permissions

Kunskap om filrättigheter och kunna ändra dessa från terminalen.

=== Varför?

För att kunna manipulera filer i CLI-baserad gränssnitt utan GUI.

=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon
[cols=">1,3,3"]
|===
| Kommando | Beskrivning | Exempel

|`sudo`
|
|

|`chown`
|
|

|`chgrp`
|
|


|`chmod`
|
|

|`umask`
|
|

|===


.Koncept
* Användare
* Grupper

=== Exempel

Bra men svår guide om rättigheter: https://help.ubuntu.com/community/FilePermissions

Kör i terminalen

* filrättigheter (ls -l / chmod)
* användare - grupper (chown / chgrp)
* root - sudo

== Kommandon för filtrering av text och filer

Använda CLI program för filtrera text och hitta filer med specifika egenskaper.


=== Varför?

För att kunna söka efter text och filer i CLI-baserat gränssnitt.


=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
[cols=">1,3,3"]
|===
| Kommando | Beskrivning | Exempel

|`head`
|
|

|`tail` & `head`
|
| Jämför `tail /var/log/messages` och `head /var/log/messages`.

|`sort`
|
|

|`wc`
|
|

|`grep`
|
|

|`find`
|
|

|===

== Streams, redirects och piping

Kunskap om indata/utdata till terminalen, filer och andra program.


=== Varför?

För att kunna använda flera CLI program tillsammans.


=== Vad?

.Standard streams:
----
stdin, stdout, stderr
----

.Operatorer:
----
>, >>, 2>, <, |
----

När du skriver ett kommando som tex. `date` syns resultatet i något som heter `stdout`. För en dator är det nästan alltid att visa resultatet på skärmen. Eftersom `Unix` i många fall används utan skärm (tex en webbserver) vill man kanske att `stdout` ska synas i tex. en loggfil. Det vanliga sättet är använda "redirect operatorn" `>`. Testa i terminalen: `date > datum.txt` och kolla att data landade i filen med `cat datum.txt`.

Inputdata eller `stdin` är för en arbetsdator normalt tangentbordet men med operatorn `<` går det att suga ut data från tex. en textfil. Prova (med exempelfilerna för kontaktlistan): `sort < contacts.txt`.

Läs: https://www.redhat.com/sysadmin/redirect-operators-bash och för att fördjupa kunskaperna: https://www.howtogeek.com/435903/what-are-stdin-stdout-and-stderr-on-linux/

Kunna använda följande operatorer.

==== Övning, pipes och operatorer

Läs: https://www.redhat.com/sysadmin/pipes-command-line-linux

| (pipe) används för att skicka vidare output från ett verktyg till nästa. Skapa två olika textfiler med kontakter. Arbeta med cat, sort och grep.

Exempelmaterial
----
contacts.txt

Bob Jones
Leslie Smith
Dana David
Susan Gee
Leonard Schmidt
Linda Gray
Terry Jones
Colin Doe
Jenny Case
Terry Jones

kontakter.txt

Jens Berggren
Emil Bengtsson
Johan Eriksson
Lana Ek
Pauline Jakobsson
Nikolina Gustavsson
Linn Forsberg

----

Se quiz 3 i Google forms. Tar upp ungefär följande:

* Hur kan du sortera en lista?
* Hur sparar du den sorterade listan?
* Hur sorterar du på efternamn?
* Hur kan du vända sorteringen?
* Hur kan du slå ihop och sortera namnen från både contacts.txt och kontakter.txt
* Hur kan du söka bland båda listorna?
* Vad gör kommandot: cat contacts.txt | sort | uniq ?


== Processer

Kunskap hur man interagerar med processer från terminalen och hur dessa samspelar med varandra.


=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.


=== Vad?

.Kort kommandon:
- CTRL + C
- CTRL + Z

.Kommandon:
- kill
- ps
- jobs
- fg
- top

.Operatorer:
- &
- &&

== Scripting och shellscripts

Kunskap hur man använder bash scripting. Läs: https://www.shellscript.sh/ För att förstå grunderna i shell programmering.

=== Varför?

För att kunna använda utveckla CLI-baserade verktyg.

=== Vad?

.Koncept:
----
Shebangs, Arguments, Variables, Envrionment variables, Escaping, Subshells, Conditionals
----

.Kommandon:
----
echo
----

== Övrigt

Kunskaper om övriga kommandon.

=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
----
man, alias, history
----
Kommandot `alias` skapar en genväg till kommandon, med eller utan nycklar, för att t.ex. spara tid. Exempel. kör i terminalen:

----
$ alias lista="ls -lah
$ lista
----