= Terminalen och POSIX

Kunskaper relaterat till anvädning av terminalen. Grundläggande kunskaper om olika skal är också nödvändigt. Bash (Bourne Again Shell) är det skal (eng. shell) som utgås ifrån i följande dokumentation.

Eftersom bash är så utspritt och väl använt är detta vad som utgås ifrån istället för ett helt POSIX-kompatibelt skal såsom dash (Debian Almquist shell).

== Navigation

Kunskap om kommandon för att navigera i terminalen och förstå absoluta och relativa sökvägar.

[discrete]
=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.

[discrete]
=== Vad?

.Kommandon:
* pwd
* cd

== Filer

Kunskap om olika filtyper, metadata och förståelse att allting är filer i unix. Använda kommandon för att manipulera filer genom följande operationer:

.Operationer
* lista
* byta namn
* skapa
* ta bort
* läsa
* skriva

[discrete]
=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.

[discrete]
=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
* ls
* cat
* rm
* mv
* cp
* touch
* mkdir
* rmdir
* less/more
* file
* du

== CLI-baserade textredigare

Kunskap att använda en eller flera textredigare ifrån terminalen.

[discrete]
=== Varför?

För att kunna manipulera filer i CLI-baserad gränssnitt utan GUI.

[discrete]
=== Vad?

* nano/vim/emacs

== Unix permissions

Kunskap om filrättigheter och kunna ändra dessa från terminalen.

[discrete]
=== Varför?

För att kunna manipulera filer i CLI-baserad gränssnitt utan GUI.

[discrete]
=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
* sudo
* chmod
* chown
* umask

.Koncept
* Användare
* Grupper

== Kommandon för filtrering av text och filer

Använda CLI program för filtrera text och hitta filer med specifika egenskaper.

[discrete]
=== Varför?

För att kunna söka efter text och filer i CLI-baserat gränssnitt.

[discrete]
=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
* head
* tail
* sort
* wc
* grep
* find

== Streams, redirects och piping

Kunskap om indata/utdata till terminalen, filer och andra program.

[discrete]
=== Varför?

För att kunna använda flera CLI program tillsammans.

[discrete]
=== Vad?

.Standard streams:
* stdin
* stdout
* stderr

Kunna använda följande operatorer.

.Operatorer:
* >
* >>
* 2>
* <
* |

== Processer

Kunskap hur man interagerar med processer från terminalen och hur dessa samspelar med varandra.

[discrete]
=== Varför?

För att kunna använda CLI-baserade utvecklingsverktyg.

[discrete]
=== Vad?

.Kort kommandon:
- CTRL + C
- CTRL + Z

.Kommandon:
- kill
- ps
- jobs
- fg
- top

.Operatorer:
- &
- &&

== Scripting

Kunskap hur man använder bash scripting.

[discrete]
=== Varför?

För att kunna använda utveckla CLI-baserade verktyg.

[discrete]
=== Vad?

.Koncept:
- Shebangs
- Arguments
- Variables
- Envrionment variables
- Escaping
- Subshells
- Conditionals

.Kommandon:
- echo

== Övrigt

Kunskaper om övriga kommandon.

[discrete]
=== Vad?

Kunna använda följande kommandon med vanliga växlar.

.Kommandon:
- man
- alias
- history
