= APL
På TE4 har vi tio veckors arbetsplatsförlagt lärande på vårterminen

== Observationsövning, APL
Uppgiften behandlar ”soft skills”, dvs. alla de icke-tekniska och luddiga sidorna av arbetet. Syftet är att observera och bli uppmärksam på hur arbetsplatsen fungerar. Vissa av frågeställningarna kan du säkert besvara direkt, medan andra kräver en riktad observation eller att du t.ex. ställer frågor till anställda på arbetsplatsen.

Skriv ungefär ett stycke under respektive rubrik. Punktlistorna beskriver ungefär vad du förväntas svara på. Arbeta gärna med detta dokumentet regelbundet under APL.

=== Arbetssätt
* Arbetar ni enligt någon utvecklingsmetodik som t.ex. Scrum? Eller finns det en egen variant?
* På vilka sätt skiljer dessa metoder mot hur ni arbetat på skolan?

=== Formella krav jämfört med praxis
* Vilka delar av arbetet styrs med regelverk som t.ex. kodstandarder, checklistor eller sekretessavtal?
* Vilka delar av arbetet styrs av "oskrivna regler" som mer “sitter i väggarna" eller arbetskultur?

=== Beslutsfattande och anställdas inflytande
* Vem fattar (eller var fattas) beslut och direktiv som påverkar utvecklarnas arbete?
* Vilket inflytande har utvecklare och ”vanliga” anställda jämfört med arbetsledare och chefer?
* Förekommer det att beslut och direktiv ifrågasätts eller motverkar varandra?

=== Villkor för team och utvecklare
* Vilka är de största hindren i arbetet för den enskilde utvecklaren eller teamen? Undersök aspekter som kommunikation (vilka former/verktyg används?), kompetens, resurser (materiella, personal), tidsramar, deadlines,etc.

=== Hållbara arbetsförhållanden
* I vilken utsträckning kan individer eller teamen själva påverka arbetstakten?
* I vilken utsträckning verkar anställda vara påverkade av stress eller oro som uppkommer av arbetet?
* Förekommer det uttryckliga krav på ökat tempo eller övertid för att möta fastställda deadlines eller milstolpar?
* Hur uppfattas eventuella höjda prestationskrav bland utvecklare och övriga anställda?
* Belönas övertid eller extra engagemang?

=== Trivsel och arbetsklimat
* Är arbetet upplagt så att man har möjligheter till samarbete och god kontakt med sina arbetskamrater?
* Ger arbetskamrater varandra stöd och hjälp om problem uppstår i arbetet?
* Hur ser det dagliga umgänget ut på arbetsplatsen? Förekommer det t ex aktiviteter som syftar till avkoppling och gemenskap (spel, lek, after-work, etc)?
* Kan man uppfatta en tydlig sammanhållning eller vi-känsla bland arbetskamraterna?

=== Konflikter och motsättningar
* Kan man uppfatta motsättningar eller konflikter på arbetsplatsen?
* Vilka aspekter av arbetet verkar konflikterna handla om? Kan man ana andra bakomliggande orsaker till konflikterna?
* Hur hanteras konflikter av chefer och arbetsledare?