= SDLC

Kunskaper relaterat till systemutveckling (eng. software development life cycle) enligt någon utvecklingsmetodik.

Utvecklingsmetodiken scrum är vad som utgås ifrån i följande dokumentation.

== Planering

Inbegripper planerings, analys och design fas från SDLC. Under processen deltar eleverna i alla scrum cermonier för sprintar.

[discrete]
=== Varför?

För att jobba i sprintar krävs en sprintplanering. Tanken är att jobba i cycklar för att i slutet av varje sprint ha en fungerande produkt.

[discrete]
=== Vad?

.Begrepp
* Tasks
* User story
* Definition of Done
* Acceptance Criteria
* Backlog
* Sprintplanering
* Sprintmål
* Sprint review
* Sprint retrospective

== Utveckling

Inbegripper utvecklingsfasen från SDLC. Jobbet som innefattas är utveckling av funktionalitet, felsökning samt buggfixar.

[discrete]
=== Varför?

För att kunna implementera planerad funktionalitet.

[discrete]
=== Vad?

Jobba både självständigt och kollaborativt med ny funktionalitet eller utarbeta/förändra existerande funktionalitet. Eleverna tillämpar strategier som exemepelvis divide and conquer för att bryta ner ett problem i mindre delar.

.Kunskaper
* Felsökning
* Läsa och söka dokuemtation
* Parprogrammering
* Code reviews
