= Appendix: Kurser, centrallt innehåll, kunskapskrav och uppföljning

== Bedömning #TODO#
Bedömning i två axlar: Hur självständigt arbetar eleven? Hur komplexa uppgifter löser eleven? + 
Bedömning görs i första hand på retrospektiven där eleven innan mötet arbetar med en självutvärdering.

=== Projekt
==== P0 - WTF
==== P1 - WTFv2
==== P2 - Teacher-o-matic
==== P3 - Log-o-matic
==== P4 - YABS

== Kurser

=== Mjukvarudesign, MD

====
https://www.skolverket.se/undervisning/gymnasieskolan/laroplan-program-och-amnen-i-gymnasieskolan/gymnasieprogrammen/amne?url=1530314731%2Fsyllabuscw%2Fjsp%2Fsubject.htm%3FsubjectCode%3DMJK%26tos%3Dgy&sv.url=12.5dfee44715d35a5cdfa92a3[*Skolverkets beskrivning, MD*]

.Centralt innehåll
* Körmiljöer och plattformar, till exempel desktop, mobil, inbyggda system och webbapplikationer. + 
<<Terminalen och Unix>>, `M6-GithubFlow`
* Utvecklingsmetodik, inklusive agila metoder. +
<<Agil systemutveckling>>, <<Observationsövning på APL>>, `M6-GithubFlow`
* Utvecklingsmiljöer och infrastrukturbehov. +
<<Linux och Docker>>, `M6-GithubFlow`
* Verktyg för projekthantering, ärendehantering och samarbete. +
<<Versionshantering>>, <<Observationsövning på APL>>, `M6-GithubFlow`
* Kodkvalitet och kodstandarder. +
<<SDLC och DevOps>>, <<Observationsövning på APL>>, `M6-GithubFlow`
* Kodanalys och kvalitetskontroll, inklusive bugghantering och automatiserade tester. + 
<<SDLC och DevOps>>, `M6-GithubFlow`
* Verktyg för versionshantering. +
<<Versionshantering>>, <<Observationsövning på APL>> , `M6-GithubFlow`
* Internationalisering och lokalisering.
* Upprättande av teknisk dokumentation, till exempel genererad från programkodskommentarer.
* Ergonomiska krav på datorarbetsplatsen.
* Paketering och distribution av mjukvara.
* Licenser och betalningsmodeller.
====

=== Gymnasieingenjören i praktiken, GIP

====
https://www.skolverket.se/undervisning/gymnasieskolan/laroplan-program-och-amnen-i-gymnasieskolan/gymnasieprogrammen/amne?url=1530314731%2Fsyllabuscw%2Fjsp%2Fsubject.htm%3FsubjectCode%3DGYN%26tos%3Dgy&sv.url=12.5dfee44715d35a5cdfa92a3[*Skolverkets beskrivning, GIP*]

.Centralt innehåll
* Etiska, sociala och historiska aspekter på ingenjörens roll. + 
`M2.1-Vad är en ingenjör?`
* Systemtänkande samt olika metoder och begrepp som är gemensamma och användbara för det ingenjörsmässiga arbetet. +
<<Agil systemutveckling>>, <<Observationsövning på APL>> , `M6-GithubFlow`
* Entreprenörskap och företagande inom teknikområdet med fokus på dess villkor, förutsättningar och behov. + 
`M23-Entreprenörskap`
* Målstyrning och behovsstyrning. + 
<<Observationsövning på APL>>
* Olika företagskulturers betydelse. + 
<<Observationsövning på APL>>
* Grundläggande företagsekonomiska teorier och begrepp inom området ekonomisk hållbarhet. Kalkylering, budgetering och projektekonomi. + 
`M23-Entreprenörskap`
* Grundläggande juridik inom teknikområdet, till exempel avtals-, arbetsmarknads-, upphandlings- och arbetsmiljörätt.
* Hur en projektplan upprättas och genomförs samt användbara verktyg, (till exempel kalkyl och budget). + 
<<Observationsövning på APL>>
* Grundläggande teorier om ledarskap och organisation, till exempel hur beslutsfattande sker i en organisation. + 
<<Observationsövning på APL>>, `M16-konflikter`
* Grupprocesser och gruppdynamik. + 
<<Observationsövning på APL>>, `M4-Grupprocesser`, `M16-konflikter`
* Naturvetenskapliga och tekniska teorier och metoder.
* Kommunikationsstrategier samt kommunikations-, dokumentations- och presentationsteknik för att förmedla teknik och information. + 
<<Observationsövning på APL>>

====

`M14-JWT`